### ISSUE TITLE
Iris demo @out const causes errors in array declaration

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieBuilderDemos#1]
Running the Iris demo ([this commit](https://github.com/GenieFramework/GenieBuilderDemos/tree/6cd79699fb9a2a6513c23cd49538f392b77eb346/iristutorial)) with Stipple 0.26 yields this error
```julia
julia> includet("app.jl")
ERROR: [ Info: 2023-03-23 16:20:12 Watching ["/Users/pere/genie/demos/GenieBuilderDemos/IrisTutorial"]
LoadError: BoundsError: attempt to access 1-element Vector{Any} at index [2]
in expression starting at /Users/pere/genie/demos/GenieBuilderDemos/IrisTutorial/app.jl:9
Stacktrace:
 [1] getindex(A::Vector{Any}, i1::Int64)
   @ Base ./array.jl:924
 [2] var"@out"(__source__::LineNumberNode, __module__::Module, expr::Any)
   @ Stipple.ReactiveTools ~/.julia/packages/Stipple/YLAxg/src/ReactiveTools.jl:300
 [3] eval
   @ ./boot.jl:368 [inlined]
 [4] process_source!(mod_exprs_sigs::OrderedDict{Module, OrderedDict{Revise.RelocatableExpr, Union{Nothing, Vector{Any}}}}, ex::Expr, filename::String, mod::Module; mode::Symbol)
   @ Revise ~/.julia/packages/Revise/P8ITN/src/parsing.jl:54
in expression starting at /Users/pere/genie/demos/GenieBuilderDemos/IrisTutorial/app.jl:9
```

The problem is with the const declaration
```julia
@out const features = [:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]
```

Now it needs to be 

```julia
@out! features = [:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]
```

**Comment by PGimenez** [comment]
@essenciary this is an example of what we discussed about the reactive model. If you use @out instead of @out!, then this code fails because the features variable does not exist

```julia
@out features = [:SepalLength, :SepalWidth, :PetalLength, :PetalWidth]

function cluster(no_of_clusters=3, no_of_iterations=10)
    feats = Matrix(data[:, [c for c in features]])' |> collect      # <--- features used here
    result = kmeans(feats, no_of_clusters; maxiter=no_of_iterations)
    data[!, :Cluster] = assignments(result)
end
```

```julia
┌ Error: 2023-03-23 16:31:08 Error attempting to invoke handler 3 for field Reactive{Bool}(Observable(true), 1, false, false, "") with value
 true
└ @ Stipple ~/.julia/packages/Stipple/YLAxg/src/stipple/mutators.jl:36
┌ Error: 2023-03-23 16:31:09
│   exception =
│    UndefVarError: features not defined
```

Somehow we need to explain that declaring `@out var` does not create a variable in the scope.

**Comment by essenciary** [comment]
That's how the code used to work before we agreed on the latest breaking changes. But again, I don't think it requires deep explanation. We just need to document the API. 

However, I don't understand why this issue exists. You were in the maintainers call where we made the decision to introduce this change. 

---

As you can see in your example, there are a lot more `@out` declaration vs `@out!` so this saves on variable allocations. However, it comes at the cost of increased complexity for the users. But if the documentation is clear, it should be fine.
